import type { Effect, EffectType } from "../types";
export function effectAmount(effect: Effect,time=0){const keys=effect.keyframes??[];if(!keys.length)return effect.parameters.amount??0;const sorted=[...keys].sort((a,b)=>a.time-b.time);if(time<=sorted[0].time)return sorted[0].value;if(time>=sorted[sorted.length-1].time)return sorted[sorted.length-1].value;for(let i=0;i<sorted.length-1;i++){const a=sorted[i],b=sorted[i+1];if(time>=a.time&&time<=b.time){const p=(time-a.time)/Math.max(.0001,b.time-a.time);return a.value+(b.value-a.value)*p;}}return effect.parameters.amount??0;}
export function effectFilter(effect:Effect,time=0):string{if(!effect.enabled)return"none";const p=effect.parameters;const a=effectAmount(effect,time);switch(effect.type){case"blur":return`blur(${Math.max(0,a)}px)`;case"pixelate":return`blur(${Math.max(0,a*.08)}px) contrast(${100+a*3}%)`;case"glow":return`drop-shadow(0 0 ${Math.max(0,a)}px rgba(255,255,255,.9))`;case"dropShadow":return`drop-shadow(${p.x??6}px ${p.y??6}px ${Math.max(0,a)}px rgba(0,0,0,.65))`;case"glitch":return`contrast(${100+a*1.2}%) saturate(${100+a*2}%) hue-rotate(${a*2}deg)`;case"brightness":return`brightness(${Math.max(0,a)}%)`;case"contrast":return`contrast(${Math.max(0,a)}%)`;case"saturate":return`saturate(${Math.max(0,a)}%)`;case"hue":return`hue-rotate(${a}deg)`;case"grayscale":return`grayscale(${Math.max(0,Math.min(100,a))}%)`;case"sepia":return`sepia(${Math.max(0,Math.min(100,a))}%)`;case"invert":return`invert(${Math.max(0,Math.min(100,a))}%)`;case"opacity":return`opacity(${Math.max(0,Math.min(100,a))}%)`;case"sharpen":return`contrast(${100+a*.5}%) saturate(${100+a*.15}%)`;case"noise":return`contrast(${100+a}%) saturate(${100+a*.4}%)`;case"vignette":return`brightness(${100-a*.15}%) contrast(${100+a*.2}%)`;case"duotone":return`grayscale(${Math.min(100,a)}%) contrast(${100+a*.3}%)`;case"posterize":return`contrast(${100+a*2}%) saturate(${100+a}%)`;case"chromatic":return`hue-rotate(${a*1.5}deg) saturate(${100+a}%)`;case"scanlines":return`contrast(${100+a*.5}%)`;case"rgbSplit":return`saturate(${100+a*2}%) hue-rotate(${a*3}deg)`;default:return"none";}}
export function combinedFilter(effects:Effect[]=[],time=0):string{return effects.filter(e=>e.enabled).map(e=>effectFilter(e,time)).filter(f=>f!=="none").join(" ")||"none";}
type Preset={type:EffectType;name:string;defaultAmount:number;min:number;max:number;unit:string};
const defs:Array<[EffectType,string,number,number,number,string]>=[["blur","Blur",8,0,40,"px"],["pixelate","Pixel Blur",8,0,30,""],["glow","Glow",12,0,40,"px"],["dropShadow","Drop Shadow",8,0,40,"px"],["glitch","Glitch",25,0,100,""],["brightness","Brightness",110,0,200,"%"],["contrast","Contrast",115,0,200,"%"],["saturate","Saturation",125,0,250,"%"],["hue","Hue Shift",25,-180,180,"°"],["grayscale","Grayscale",100,0,100,"%"],["sepia","Sepia",60,0,100,"%"],["invert","Invert",100,0,100,"%"],["opacity","Opacity",80,0,100,"%"],["sharpen","Sharpen",40,0,100,""],["noise","Noise",20,0,100,""],["vignette","Vignette",35,0,100,""],["duotone","Duotone",55,0,100,""],["posterize","Posterize",25,0,100,""],["chromatic","Chromatic",30,0,100,""],["scanlines","Scanlines",35,0,100,""],["rgbSplit","RGB Split",25,0,100,""]];
const base:Preset[]=defs.map(([type,name,defaultAmount,min,max,unit])=>({type,name,defaultAmount,min,max,unit}));
const variants=["Soft","Strong","Dream","Night","Retro","Crisp","Film","Neon","Cyber","Old TV","VHS","Faded","Punchy","Soft Light","Hard Light","Electric","Frost","Heat","Mono","Dark","Bright","Deep","Pastel","Drama","Action","Comic","Digital","Analog","Mystic","Shadow","Clean","Epic","Warm","Cool","Urban","Vintage","Cinema","Flash","Twist","Distort"];export const EFFECT_PRESETS:Preset[]=[...base,...variants.map((name,i)=>{const b=base[i%base.length];return{...b,name:`${name} ${b.name}`,defaultAmount:Math.max(b.min,Math.min(b.max,b.defaultAmount+((i%5)-2)*5))}})];
export const FILTER_PRESETS=[{name:"Warm Cinema",values:[{type:"brightness" as const,amount:105},{type:"contrast" as const,amount:115},{type:"saturate" as const,amount:120}]},{name:"Cool Cinema",values:[{type:"brightness" as const,amount:102},{type:"contrast" as const,amount:112},{type:"hue" as const,amount:-12}]},{name:"Vintage Film",values:[{type:"sepia" as const,amount:35},{type:"contrast" as const,amount:108},{type:"saturate" as const,amount:85}]},{name:"Black & White",values:[{type:"grayscale" as const,amount:100},{type:"contrast" as const,amount:112}]},{name:"Dream",values:[{type:"blur" as const,amount:2},{type:"brightness" as const,amount:108},{type:"saturate" as const,amount:115}]},{name:"Cyber",values:[{type:"glitch" as const,amount:35},{type:"contrast" as const,amount:125},{type:"hue" as const,amount:35}]}];
