import { Diamond, Lock, LockOpen, MousePointerSquareDashed, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { editorStore, useEditor } from "../store";
import { findClip, type AnimatableProperty, type Clip, type TextStyle } from "../types";
import { valueAt } from "../render/keyframes";
import { EFFECT_PRESETS, FILTER_PRESETS } from "../render/effects";
import { timecode } from "../format";

const textPresets = ["Clean","Bold","Neon","Outline","Shadow","Cinema","Retro","VHS","Cyber","Minimal","Modern","Classic","Comic","Gaming","Luxury","Typewriter","Headline","Caption","Glow","Electric"];
const textPresetStyles: TextStyle[] = textPresets.flatMap((name, i) => Array.from({ length: 6 }, (_, v) => ({
  fontFamily: ["Barlow, sans-serif","Impact, sans-serif","Georgia, serif","Verdana, sans-serif","'Courier New', monospace","'Trebuchet MS', sans-serif"][v], fontSize: [72,88,104,120,64,140][v], bold: i % 3 !== 0, italic: v === 2, underline: false,
  align: "center" as const, color: ["#ffffff","#00e5ff","#ff4d6d","#ffd166","#7cff6b","#b388ff"][v], colorOpacity: 100,
  backgroundEnabled: name === "Caption", backgroundColor: "#000000", backgroundOpacity: 65, padding: 18 + v * 2, borderRadius: 8 + v, strokeWidth: name === "Outline" ? 3 : v % 3, strokeColor: "#000000"
})));

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <div className="border-b border-border p-3"><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{title}</div><div className="space-y-2">{children}</div></div>; }
function Field({ label, value, suffix, onChange }: { label: string; value: number; suffix?: string; onChange: (v: number) => void }) { return <label className="flex items-center gap-2 text-[11px]"><span className="w-16 text-muted-foreground">{label}</span><input className="field-input flex-1" type="number" value={Math.round(value)} onChange={(e) => onChange(Number(e.target.value))}/>{suffix ? <span className="text-[10px] text-muted-foreground">{suffix}</span> : null}</label>; }
function Anim({ clip, property, label, min, max }: { clip: Clip; property: AnimatableProperty; label: string; min: number; max: number }) { const time = useEditor(s => s.currentTime); const v = valueAt(clip, property, time - clip.timelineStart); const has = clip.keyframes.some(k => k.property === property); const here = clip.keyframes.some(k => k.property === property && Math.abs(k.time - (time - clip.timelineStart)) < .02); return <div><div className="flex items-center justify-between text-[11px]"><span>{label}</span><button type="button" title="Toggle keyframe" onClick={() => editorStore.toggleKeyframe(clip.id, property)} className={here || has ? "text-primary" : "text-muted-foreground"}><Diamond className={`h-3 w-3 ${here ? "fill-current" : ""}`}/></button></div><input className="w-full accent-primary" type="range" min={min} max={max} value={v} onChange={e => editorStore.setAnimatable(clip.id, property, Number(e.target.value), true)}/></div>; }

export function InspectorPanel({ aspectLocked, onToggleAspect }: { aspectLocked: boolean; onToggleAspect: () => void }) {
  const project = useEditor(s => s.project); const selectedId = useEditor(s => s.selectedClipId); const currentTime = useEditor(s => s.currentTime); const [tab, setTab] = useState<"properties"|"effects"|"color">("properties");
  const found = useMemo(() => findClip(project, selectedId), [project, selectedId]);
  if (!found) return <aside className="flex w-80 shrink-0 flex-col border-l border-border bg-panel"><div className="panel-header">Inspector</div><div className="flex flex-1 flex-col items-center justify-center gap-2 p-6 text-center"><MousePointerSquareDashed className="h-6 w-6 text-muted-foreground"/><p className="text-xs text-muted-foreground">Select a clip to open Properties, Effects Control and Color.</p></div></aside>;
  const { clip } = found; const t = clip.transform; const isText = clip.type === "text";
  const addEffect = (preset: typeof EFFECT_PRESETS[number]) => editorStore.edit(p => { const c = findClip(p, clip.id)?.clip; if (c) (c.effects ??= []).push({ id: `fx_${Math.random().toString(36).slice(2)}`, type: preset.type, name: preset.name, enabled: true, parameters: { amount: preset.defaultAmount }, keyframes: [] }); });
  const updateEffect = (id: string, patch: (e: NonNullable<Clip["effects"]>[number]) => void) => editorStore.edit(p => { const c = findClip(p, clip.id)?.clip; const e = c?.effects?.find(x => x.id === id); if (e) patch(e); });
  const setColor = (type: "brightness"|"contrast"|"saturate"|"hue"|"sepia"|"grayscale", amount: number) => editorStore.edit(p => { const c = findClip(p, clip.id)?.clip; if (!c) return; const e = c.effects?.find(x => x.type === type); if (e) e.parameters.amount = amount; else (c.effects ??= []).push({ id: `fx_${type}_${Date.now()}`, type, name: type[0].toUpperCase()+type.slice(1), enabled: true, parameters: { amount }, keyframes: [] }); });
  return <aside className="flex w-80 shrink-0 flex-col overflow-hidden border-l border-border bg-panel">
    <div className="panel-header justify-between"><span>Inspector · {clip.name}</span><button type="button" onClick={() => editorStore.deleteClip(clip.id)} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5"/></button></div>
    <div className="grid grid-cols-3 border-b border-border"><button className={`py-2 text-[10px] font-semibold ${tab === "properties" ? "border-b-2 border-primary" : "text-muted-foreground"}`} onClick={() => setTab("properties")}>Properties</button><button className={`py-2 text-[10px] font-semibold ${tab === "effects" ? "border-b-2 border-primary" : "text-muted-foreground"}`} onClick={() => setTab("effects")}>Effects Control</button><button className={`py-2 text-[10px] font-semibold ${tab === "color" ? "border-b-2 border-primary" : "text-muted-foreground"}`} onClick={() => setTab("color")}>Color</button></div>
    <div className="min-h-0 flex-1 overflow-y-auto">
    {tab === "properties" ? <>
      {isText ? <Section title="Text"><textarea className="field-input min-h-16 w-full" value={clip.text ?? ""} onChange={e => editorStore.updateText(clip.id, e.target.value)}/><div className="grid grid-cols-3 gap-1">{textPresetStyles.map((style, i) => <button key={i} type="button" title={`Text preset ${i+1}`} onClick={() => editorStore.updateStyle(clip.id, style)} className="rounded border border-border p-1 text-[9px] hover:border-primary" style={{ fontFamily: style.fontFamily, color: style.color }}>Preset {i+1}</button>)}</div><div className="text-[9px] text-muted-foreground">100+ typography presets</div></Section> : null}
      <Section title="Transform"><Field label="X" value={valueAt(clip,"x",currentTime-clip.timelineStart)} suffix="px" onChange={v => editorStore.setAnimatable(clip.id,"x",v)}/><Field label="Y" value={valueAt(clip,"y",currentTime-clip.timelineStart)} suffix="px" onChange={v => editorStore.setAnimatable(clip.id,"y",v)}/><Field label="Width" value={valueAt(clip,"width",currentTime-clip.timelineStart)} suffix="px" onChange={v => { editorStore.setAnimatable(clip.id,"width",v); if (aspectLocked) editorStore.setAnimatable(clip.id,"height",Math.round(v*t.height/t.width)); }}/><Field label="Height" value={valueAt(clip,"height",currentTime-clip.timelineStart)} suffix="px" onChange={v => { editorStore.setAnimatable(clip.id,"height",v); if (aspectLocked) editorStore.setAnimatable(clip.id,"width",Math.round(v*t.width/t.height)); }}/><button type="button" onClick={onToggleAspect} className="flex w-full items-center gap-2 rounded border border-border p-1.5 text-[10px]">{aspectLocked ? <Lock className="h-3 w-3"/> : <LockOpen className="h-3 w-3"/>} Lock aspect</button><Anim clip={clip} property="rotation" label="Rotation" min={-180} max={180}/><Anim clip={clip} property="scale" label="Scale" min={1} max={300}/><Anim clip={clip} property="opacity" label="Opacity" min={0} max={100}/></Section>
      <Section title="Timing"><div className="text-[10px] text-muted-foreground">In {timecode(clip.timelineStart,true)} · Out {timecode(clip.timelineStart+clip.duration,true)}</div></Section>
      <Section title="Keyframes"><div className="grid grid-cols-2 gap-1">{(["x","y","width","height","rotation","scale","opacity"] as AnimatableProperty[]).map(p => <button key={p} type="button" onClick={() => editorStore.toggleKeyframe(clip.id,p)} className="rounded border border-border p-1 text-[9px] hover:border-primary"><Diamond className="mr-1 inline h-3 w-3"/>{p}</button>)}</div></Section>
    </> : null}
    {tab === "effects" ? <div className="p-3"><div className="mb-2 text-[10px] text-muted-foreground">Click or drag an effect onto a timeline clip. Effects are stored per clip.</div><div className="grid grid-cols-2 gap-1.5">{EFFECT_PRESETS.map((p,i)=><button draggable key={i} type="button" onDragStart={e=>{e.dataTransfer.setData("application/x-edit-suite-effect",JSON.stringify(p));e.dataTransfer.effectAllowed="copy"}} onClick={()=>addEffect(p)} className="rounded border border-border p-2 text-left text-[10px] hover:border-primary">{p.name}</button>)}</div><div className="mt-4 space-y-2">{(clip.effects ?? []).map(effect=><div key={effect.id} className="rounded border border-border p-2"><div className="flex items-center justify-between text-[10px] font-semibold"><span>{effect.name}</span><button onClick={()=>editorStore.edit(p=>{const c=findClip(p,clip.id)?.clip;if(c)c.effects=(c.effects??[]).filter(x=>x.id!==effect.id)})}>×</button></div><input type="range" min={EFFECT_PRESETS.find(x=>x.type===effect.type)?.min??0} max={EFFECT_PRESETS.find(x=>x.type===effect.type)?.max??100} value={effect.parameters.amount??0} onChange={e=>updateEffect(effect.id,x=>x.parameters.amount=Number(e.target.value))} className="w-full accent-primary"/><div className="flex justify-between text-[9px] text-muted-foreground"><span>{effect.parameters.amount ?? 0}</span><button title="Add effect keyframe" onClick={()=>updateEffect(effect.id,x=>{const local=currentTime-clip.timelineStart;(x.keyframes??=[]);const k=x.keyframes.find(k=>Math.abs(k.time-local)<.02);if(k)k.value=x.parameters.amount??0;else x.keyframes.push({id:`k_${Date.now()}`,property:"opacity",time:local,value:x.parameters.amount??0,easing:"linear"})})}><Diamond className="inline h-3 w-3"/> Keyframe</button></div></div>)}</div></div> : null}
    {tab === "color" ? <div className="p-3"><div className="mb-3 text-[10px] text-muted-foreground">Manual color adjustment</div>{([['brightness',0,200],['contrast',0,200],['saturate',0,250],['hue',-180,180],['sepia',0,100],['grayscale',0,100]] as const).map(([type,min,max])=><label key={type} className="mb-3 block text-[10px] capitalize">{type}<input className="mt-1 w-full accent-primary" type="range" min={min} max={max} value={type==='hue'?0:100} onChange={e=>setColor(type,Number(e.target.value))}/></label>)}<div className="mb-2 mt-4 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Presets</div><div className="grid grid-cols-2 gap-1">{FILTER_PRESETS.map(p=><button key={p.name} onClick={()=>editorStore.edit(pr=>{const c=findClip(pr,clip.id)?.clip;if(c)c.effects=p.values.map(v=>({id:`fx_${Date.now()}_${v.type}`,type:v.type,name:v.type,enabled:true,parameters:{amount:v.amount},keyframes:[]}))})} className="rounded border border-border p-2 text-[10px] hover:border-primary">{p.name}</button>)}</div></div> : null}
    </div>
  </aside>;
}
